# Generated by Django 4.2.1 on 2023-06-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_containers_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='containers',
            name='color',
            field=models.CharField(default='nothing', max_length=10),
        ),
    ]
