# Generated by Django 4.2.1 on 2023-08-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='status',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
