# Generated by Django 4.2.1 on 2023-08-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_tails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tails',
        ),
    ]
